#!/bin/bash

mkdir -p "$HOME/exam-backups"

TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

tar -czf \
"$HOME/exam-backups/final-exam-$TIMESTAMP.tar.gz" \
-C "$HOME/OS-SE-p20240032" final-exam

echo "Backup completed."
